all:
    gcc server.c addMoney.c deleteCard.c insertCard.c insertTrans.c loginFunction.c registerIbanNull.c showAllTrans.c showBalance.c showCards.c showTotalBalance.c showTrans.c writeToClient.c working.c report.c save.c exit.c logout.c -o server -lsqlite3
    gcc client.c -o client

clean:
    rm -f server client
